/* Fig. 5.7: fig05_07.c
    Simulating dice toss
    Shifted, scaled integers produced by 1 + rand() % 6
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    int i;

    srand( time(NULL) ); //Random seed generated by unix time

    for ( i = 1; i <= 20; i++)
    {
        printf("%10d", 1 + ( rand() % 6 ) );

        if (i % 5 == 0){
            printf( "\n" );
        }
    }
    

    return 0;
}